sudo: false
language: node_js

addons:
  apt:
    packages:
    - sshpass

node_js:
  - '9'

before_script: 
  - echo D_PATH
  - echo '开始安装依赖~~~'
  - yarn
  - echo '依赖安装完毕~~~'
script: 
  - echo '开始编译项目~~~'
  - yarn build
  - echo '项目编译成功~~~'

  - echo ./${D_LOCAL}
  
  - echo '开始推送~~~'
  - sshpass -p D_PS scp -o stricthostkeychecking=no -r ./${D_LOCAL} ${D_SERVER}:${D_PATH}
  - echo '推送成功~~~'
  
env:
  - D_PS=X_PS
  - D_SERVER=X_SERVER
  - D_PATH=X_PATH
  - D_LOCAL=X_LOCAL
