sudo: false
language: node_js

addons:
  apt:
    packages:
    - sshpass

node_js:
  - '9'

before_script: 
  - yarn

script: 
  - echo ${X_TEST}
  - yarn build
  - sshpass -p ${X_PS} scp -o stricthostkeychecking=no -r ./${X_LOCAL} ${X_SERVER}:${X_PATH}
